### ISSUE TITLE
Instruction for testing

### ISSUE THREAD

**Issue by kaphleamrit2** [liutianlin0121/ISTA-U-Net#1]
Could you provide guidance on evaluating the trained model? Additionally, is it feasible to obtain the weights from the trained model?

Thanks.

**Comment by liutianlin0121** [comment]
Thank you very much for your interest. I am currently in the process of refactoring the code. Due to compute resource constraints, I plan to re-run the experiments with the refactored code during the Easter holiday. I'll get back to you in mid April.

**Comment by liutianlin0121** [comment]
Hi! I have updated the readme, where you can find Google colabs and checkpoints for experimenting with MUSC. Have fun! ;-)
